language: python
python:
- 2.7
install:
- pip install tox-travis
script:
- tox
notifications:
  slack:
    secure: J/3aYjiD0cCKbaZnpP1QPhcaiQvTh9i1iagfcHQt2RejPPKEuqsAVQGbPAlGC2oqzOgJgXwwXMGUGVHCuJyeyrzMY6jCZUWZmiUeIYFMBwR0RVN4Kd8rB/Xes/kacv/ebsK6ky9mXKM7VZXxErxFCJJxtA8pAIeQkb1X8vzCM/lJCekWf1ix+cuhS7osy9BR1b+yvAPUexMsG2+hO9WFH752lfbBxnMbGjQ4qIrxYNRhO0rEkLDotelxJh2b8Wd/XrT33evZTthDl/xFrff1vhp7BkLNtpSlxnUyxSLwaJOLQUeBXIS9TZY3wiU5NlSKPBC0AzVmzFwVGl5uGvYlrq4+2CLCVg1MYTSID9ptp5XtBN8JeKdMTE71wNEFf51iaR8RY+MMSImacSrV8A1DyTLGWuICirGG6p1S5z0r0xJ2rNcQoZxH7eKy/kbZtRYSjqknfmNdtbZt8lcyjSgu6292rmbqgDlodb0+lZfxnMBI/U84Jnj3o1EOk6N4GiMn4j21BulbO2o35XVlcDGvYdTnvmza3ZBC9qqFcfZBHvQkXAQPiqfMvobxn5i7jHOrTgtu6+t5VCF7+tKyDgiXApGh6VKbt2ktaZ9qSke3+QYWtUHLDbJzn4mFg5qdbRjS1ooyli3teXGfeRaSfKWS2ZNFkKOZA9FV4Uvc+bjGKv8=
