language: python
python:
- 2.7
install:
- pip install tox-travis
script:
- tox
notifications:
  slack:
    rooms:
      secure: Knyx0oeMHvsganHDVLK1mx7+TCi1nBp5/shz1thZGqwVh0UwZT1h4oYUTBrWVC1VQ/ByqF2PB3q4ka9tmgMtlPANy1LwZmqT13RVOZ4LntTj6/aT766i6TOz1/7Olk1RJJfJAsYMjCo52eQnevkVLdRSBZLDYAZ1+Np/nWZn6ytKls/m7gzFZiqblNpQ0jb5LgmOULEMwy9zlapqpcIhTZbvRhmo57kiC1AVnFNmOXrPRV2LbirfxtS44bSWD+yge0s+Zi+80L7aYJSUE43+57J3sS7yLne3A+hOVaKlb3npEE/gc4oP/WDpuDc2SC/R+lYAgRXNTb+/pxsWkS6R5neMPefoweor2igpl74TZI7QKaKrztBflsrzupSdw52eWi+7oGIYD9yvW1btJY0H4jKWlqddhDbTmJUfR3jTrwTO59g6SDXNFUL8tJnykUtJ/zaXh2d7V/HEutVzLNg43aeGggZfQMSEYzVA0iTbbQLR/SlyUxSKO1RbjktuLZZ+j5TH7Vhla0uO4+4+y2KJOVV1r3pJ0564e6uQbeCebRuWJqYf6NmHKnnF4Aah4rMA+4JEUCFOHzElSgCJC+1yzpEZAAu6BE8TJSD4WnhNWUxShgPkwMrNPWzwdEMD75DoJoqbm5WWKi6wQmhONTTU10Rbj3JcLLeJotxOROIWLO0=
    on_success: change
    on_failure: always
