# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:24


from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_streamfield_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcarouselitem',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventpagecarouselitem',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagecarouselitem',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='reviewpagecarouselitem',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='richtextpagecarouselitem',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
