# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:52


import cms.models.streamfield
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_withintroduction_alter_field_to_streamfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richtextpage',
            name='body',
            field=wagtail.core.fields.StreamField([(b'h2', wagtail.core.blocks.CharBlock(classname='title', icon='title')), (b'h3', wagtail.core.blocks.CharBlock(classname='title', icon='title')), (b'h4', wagtail.core.blocks.CharBlock(classname='title', icon='title')), (b'h5', wagtail.core.blocks.CharBlock(classname='title', icon='title')), (b'intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), (b'pullquote', wagtail.core.blocks.StructBlock([(b'quote', wagtail.core.blocks.TextBlock('quote title')), (b'attribution', wagtail.core.blocks.CharBlock())])), (b'image', wagtail.core.blocks.StructBlock([(b'image', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock()), (b'alignment', cms.models.streamfield.ImageFormatChoiceBlock())], icon='image', label='Aligned image')), (b'link', wagtail.core.blocks.StructBlock([(b'page', wagtail.core.blocks.PageChooserBlock(icon='wagtail', required=False)), (b'url', wagtail.core.blocks.URLBlock(icon='link', required=False)), (b'document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False)), (b'email', cms.models.streamfield.EmailBlock(icon='mail', required=False)), (b'label', wagtail.core.blocks.CharBlock(max_length=32))])), (b'embed', wagtail.embeds.blocks.EmbedBlock(icon='media')), (b'html', wagtail.core.blocks.StructBlock([(b'html', wagtail.core.blocks.RawHTMLBlock()), (b'alignment', cms.models.streamfield.HTMLAlignmentChoiceBlock())], label='Raw HTML')), (b'map_html', wagtail.core.blocks.StructBlock([(b'html', wagtail.core.blocks.RawHTMLBlock()), (b'alignment', cms.models.streamfield.HTMLAlignmentChoiceBlock())], label='Map HTML'))]),
        ),
    ]
