# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('taggit', '0002_auto_20150616_2121'),
        ('cms', '0005_richtextpage_alter_field_body_to_streamfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.EventPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_eventpagetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='eventpagecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='eventpagecategory',
            name='page',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='gallerycollection',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='gallerycollection',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='gallerycollection',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='gallerycollection',
            name='page',
        ),
        migrations.RemoveField(
            model_name='reviewindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='reviewindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='reviewindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='reviewindexpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='reviewpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='reviewpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='reviewpagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reviewpagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='reviewpagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='reviewpagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='reviewpagecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reviewpagecategory',
            name='page',
        ),
        migrations.RemoveField(
            model_name='reviewpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='reviewpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='reviewpagerelatedlink',
            name='page',
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
        migrations.DeleteModel(
            name='EventPageCategory',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryCollection',
        ),
        migrations.DeleteModel(
            name='ReviewIndexPage',
        ),
        migrations.DeleteModel(
            name='ReviewIndexPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='ReviewPage',
        ),
        migrations.DeleteModel(
            name='ReviewPageCarouselItem',
        ),
        migrations.DeleteModel(
            name='ReviewPageCategory',
        ),
        migrations.DeleteModel(
            name='ReviewPageRelatedLink',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.EventPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
