# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_add_symposium_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symposiumpage',
            name='date_to',
            field=models.DateField(verbose_name='End date'),
        ),
    ]
