# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 09:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('cms', '0008_alter_sumposiumpage_date_to_not_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symposiumindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='symposiumindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='symposiumindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='symposiumindexpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='symposiumpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='symposiumpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='symposiumpagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='symposiumpagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='symposiumpagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='symposiumpagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='symposiumpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='symposiumpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='symposiumpagerelatedlink',
            name='page',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='is_symposium',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SymposiumIndexPage',
        ),
        migrations.DeleteModel(
            name='SymposiumIndexPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='SymposiumPage',
        ),
        migrations.DeleteModel(
            name='SymposiumPageCarouselItem',
        ),
        migrations.DeleteModel(
            name='SymposiumPageRelatedLink',
        ),
    ]
