# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_resourcesindexpage_resourcesindexpagerelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcarouselitem',
            name='caption',
            field=models.CharField(blank=True, max_length=38),
        ),
        migrations.AlterField(
            model_name='eventpagecarouselitem',
            name='caption',
            field=models.CharField(blank=True, max_length=38),
        ),
        migrations.AlterField(
            model_name='homepagecarouselitem',
            name='caption',
            field=models.CharField(blank=True, max_length=38),
        ),
        migrations.AlterField(
            model_name='richtextpagecarouselitem',
            name='caption',
            field=models.CharField(blank=True, max_length=38),
        ),
    ]
