# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alterfield_carousel_item_caption_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='is_school',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
