# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 17:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_eventpage_is_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'News Index Page'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'News Post'},
        ),
    ]
